enableSignups:
  description: Allow users to sign up
  category: Login
  type: boolean
  default: true
  public: true

showLoginLink:
  description: Show the login button
  category: Login
  type: boolean
  default: true
  public: true

sidebarPosition:
  description: Position of the sidebar
  category: Layout
  type: string
  default: right
  public: true

maxAdmins:
  description: The maximum number of admins allowed
  category: Admin
  type: integer
  default: 1
