enableSignups:
  description: Allow users to sign up
  category: Login
  type: boolean
  default: true

maxAdmins:
  description: The maximum number of admins allowed
  category: Admin
  type: integer
  default: 1
