enableSignups:
  description: Allow users to sign up
  category: Login
  type: toggle
  default: true
  public: true

showLoginLink:
  description: Show the login button
  category: Login
  type: toggle
  default: true
  public: true

maxAdmins:
  description: The maximum number of admins allowed
  category: Admin
  type: integer
  default: 1

maxUploadFiles:
  description: The maximum number of files allowed to be uploaded at once
  category: Admin
  type: integer
  default: 10

maxUploadSize:
  description: The maximum size of upload files allowed in MB
  category: Admin
  type: integer
  default: 50

replaceCameraNames:
  description: Replace camera names when uploading images
  category: Metadata
  type: textpairs
  default: []

replaceLensNames:
  description: Replace lens names when uploading images
  category: Metadata
  type: textpairs
  default: []
