name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}

concurrency:
  group: build-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  format:
    name: Format
    uses: ./.github/workflows/format.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build-and-push:
    name: Build and push ${{ matrix.title }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - format
      - test

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: ai
            context: ./ai
            dockerfile: ./ai/Dockerfile
            title: AI
          - id: api
            context: .
            dockerfile: ./api/Dockerfile
            title: API
          - id: client
            context: .
            dockerfile: ./client/Dockerfile
            title: Client

    steps:
      - name: Checkout (${{ matrix.title }})
        uses: actions/checkout@v5

      - name: Set up Docker Buildx (${{ matrix.title }})
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container Registry (${{ matrix.title }})
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata (${{ matrix.title }})
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}-${{ matrix.id }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build & Push (${{ matrix.title }})
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.id }}
          cache-to: type=gha,mode=max,scope=${{ matrix.id }}
